In [1]:
import pandas as pd
from pathlib import Path

# Define project paths
DATA_DIR = Path("../data")

old_path = DATA_DIR / "kdrama_kaggle_1500.csv"
new_path = DATA_DIR / "kdramas_2021_2025_raw.csv"

# Load datasets
old_df = pd.read_csv(old_path)
new_df = pd.read_csv(new_path)

print("Old dataset shape:", old_df.shape)
print("New dataset shape:", new_df.shape)

Old dataset shape: (1647, 13)
New dataset shape: (508, 14)

In [2]:
print("Old dataset columns:")
print(old_df.columns.tolist())

print("\nNew dataset columns:")
print(new_df.columns.tolist())

Old dataset columns:
['Name', 'Year', 'Genre', 'Main Cast', 'Sinopsis', 'Score', 'Content Rating', 'Tags', 'Network', 'img url', 'Episode', 'Unnamed: 11', 'Unnamed: 12']

New dataset columns:
['Unnamed: 0', 'title', 'rating', 'genres', 'votes', 'synopsis', 'mainLead1', 'mainLead2', 'startYear', 'endYear', 'writer', 'director', 'id', 'image_url']

In [3]:
old_df.head()

,Name,Year,Genre,Main Cast,Sinopsis,Score,Content Rating,Tags,Network,img url,Episode,Unnamed: 11,Unnamed: 12
0,Move to Heaven,2021,"Life, Drama","Lee Je Hoon, Tang Jun Sang, Hong Seung Hee, Ju...",Han Geu Roo is an autistic 20-year-old. He wor...,9.2,18+ Restricted (violence & profanity),"Uncle-Nephew Relationship,, Autism,, Death,, S...",Netflix,https://i.mydramalist.com/Rle36_4c.jpg?v=1,10 episodes,NaN,NaN
1,Weak Hero Class 1,2022,"Action, Youth, Drama","Park Ji Hoon, Choi Hyun Wook, Hong Kyung, Kim ...",Yeon Shi Eun is a model student who ranks at t...,9.1,18+ Restricted (violence & profanity),"Smart Male Lead,, Bromance,, School Bullying,,...","Wavve, iQIYI, Viki",https://i.mydramalist.com/pq2lr_4c.jpg?v=1,8 episodes,NaN,NaN
2,Hospital Playlist Season 2,2021,"Romance, Life, Drama, Medical","Jo Jung Suk, Yoo Yeon Seok, Jung Kyung Ho, Kim...",Everyday is extraordinary for five doctors and...,9.1,15+ - Teens 15 or older,"Multiple Mains,, Band,, Music,, Strong Female ...","TVING, Netflix",https://i.mydramalist.com/dKY0d_4c.jpg?v=1,12 episodes,NaN,NaN
3,Flower of Evil,2020,"Thriller, Romance, Crime, Melodrama","Lee Joon Gi, Moon Chae Won, Jang Hee Jin, Seo ...",Although Baek Hee Sung is hiding a dark secret...,9.1,15+ - Teens 15 or older,"Deception,, Family Secret,, Mystery,, Suspense...","Prime Video, Apple TV, Viki, Netflix",https://i.mydramalist.com/WAEAp_4c.jpg?v=1,16 episodes,NaN,NaN
4,Hospital Playlist,2020,"Romance, Life, Drama, Medical","Jo Jung Suk, Yoo Yeon Seok, Jung Kyung Ho, Kim...","""The stories of people going through their day...",9.1,15+ - Teens 15 or older,"Nice Male Lead,, Multiple Mains,, Slow Romance...",Netflix,https://i.mydramalist.com/RXXL6_4c.jpg?v=1,12 episodes,NaN,NaN

In [4]:
new_df.head()

,Unnamed: 0,title,rating,genres,votes,synopsis,mainLead1,mainLead2,startYear,endYear,writer,director,id,image_url
0,0,"Genie, Make a Wish",6.4,"Comedy,Fantasy,Romance",7700,"Jinn, a genie who awakens after a thousand yea...",Kim Woo-bin,Bae Suzy,2025-01-01,2025-01-01,['Kim Eun-sook'],['Lee Byeong-heon'],tt32409807,https://m.media-amazon.com/images/M/MV5BOWM4Mj...
1,1,Squid Game,8.0,"Action,Drama,Mystery",723000,Hundreds of cash-strapped players accept a str...,Lee Jung-jae,Greg Chun,2021-01-01,2021-01-01,['Hwang Dong-hyuk'],['Hwang Dong-hyuk'],tt10919420,https://m.media-amazon.com/images/M/MV5BYTU3ZD...
2,2,When Life Gives You Tangerines,9.1,"Drama,History,Romance",29000,"In Jeju, a spirited girl and a steadfast boy's...",IU,IU,2025-01-01,2025-01-01,"['Im Sang-choon', 'Lim Sang-Chung', 'Kim Won-s...",['Kim Won-seok'],tt26471411,https://m.media-amazon.com/images/M/MV5BZTBhZT...
3,3,Typhoon Family,8.1,Drama,296,"CEO Kang Tae Pung runs Typhoon Company, his fa...",Lee Jun-ho,Minha Kim,2025-01-01,2025-01-01,['\\N'],['Lee Na-jeong'],tt36856846,https://m.media-amazon.com/images/M/MV5BYzhkZT...
4,5,All of Us Are Dead,7.6,"Action,Drama,Fantasy",85000,A high school becomes ground zero for a zombie...,Park Ji-hu,Yoon Chan-young,2022-01-01,2022-01-01,"['Seong-il Cheon', 'Joo Dong-Geun']","['J.Q. Lee', 'Kim Nam-Soo']",tt14169960,https://m.media-amazon.com/images/M/MV5BZDY4Zm...

In [5]:
print("Old dataset missing values:")
display(old_df.isna().sum().sort_values(ascending=False))

print("New dataset missing values:")
display(new_df.isna().sum().sort_values(ascending=False))

Old dataset missing values:

Unnamed: 11       1647
Unnamed: 12       1645
Tags                19
Sinopsis             5
Name                 0
Year                 0
Genre                0
Main Cast            0
Score                0
Content Rating       0
Network              0
img url              0
Episode              0
dtype: int64

New dataset missing values:

synopsis      4
Unnamed: 0    0
title         0
rating        0
genres        0
votes         0
mainLead1     0
mainLead2     0
startYear     0
endYear       0
writer        0
director      0
id            0
image_url     0
dtype: int64

## Schema Mapping

The original K-drama dataset and the new 2021–2025 dataset use different column names and slightly different structures. To keep the existing Streamlit project intact, both datasets will be standardized into one common schema before being merged.

| Final Column Name | Old Dataset Column | New Dataset Column | Notes |
|---|---|---|---|
| title | Name | title | Main drama title |
| normalized_title | generated | generated | Used for fuzzy matching and deduplication |
| start_year | Year | startYear | Drama start year |
| end_year | Year | endYear | Old dataset has only one year, so end_year will use Year |
| genres | Genre | genres | Genre/category information |
| cast | Main Cast | mainLead1 + mainLead2 | New dataset only has two lead actors |
| main_lead_1 | missing | mainLead1 | First lead actor |
| main_lead_2 | missing | mainLead2 | Second lead actor |
| synopsis | Sinopsis | synopsis | Drama description |
| global_rating | Score | rating | Public/global rating |
| content_rating | Content Rating | missing | Available only in old dataset |
| tags | Tags | missing | Available only in old dataset |
| platform | Network | missing | New dataset will use "Unknown" |
| poster_url | img url | image_url | Poster/image link |
| episodes | Episode | missing | Available only in old dataset |
| votes | missing | votes | Available only in new dataset |
| writer | missing | writer | Available only in new dataset |
| director | missing | director | Available only in new dataset |
| source_dataset | generated | generated | Tracks source file |

In [7]:
import re
import numpy as np

def normalize_title(title):
    """
    Standardizes drama titles so fuzzy matching and deduplication work better.
    Example:
    'Crash Landing on You!' -> 'crash landing on you'
    """
    if pd.isna(title):
        return ""
    
    title = str(title).lower()
    title = re.sub(r"[^a-z0-9\s]", "", title)
    title = re.sub(r"\s+", " ", title).strip()
    
    return title

Standardize the old dataset

In [8]:
old_clean = pd.DataFrame()

old_clean["title"] = old_df["Name"]
old_clean["normalized_title"] = old_clean["title"].apply(normalize_title)

old_clean["start_year"] = pd.to_numeric(old_df["Year"], errors="coerce")
old_clean["end_year"] = pd.to_numeric(old_df["Year"], errors="coerce")

old_clean["genres"] = old_df["Genre"]
old_clean["cast"] = old_df["Main Cast"]

old_clean["main_lead_1"] = np.nan
old_clean["main_lead_2"] = np.nan

old_clean["synopsis"] = old_df["Sinopsis"]
old_clean["global_rating"] = pd.to_numeric(old_df["Score"], errors="coerce")

old_clean["content_rating"] = old_df["Content Rating"]
old_clean["tags"] = old_df["Tags"]
old_clean["platform"] = old_df["Network"]
old_clean["poster_url"] = old_df["img url"]
old_clean["episodes"] = old_df["Episode"]

old_clean["votes"] = np.nan
old_clean["writer"] = np.nan
old_clean["director"] = np.nan

old_clean["source_dataset"] = "original_1500"

old_clean.head()

,title,normalized_title,start_year,end_year,genres,cast,main_lead_1,main_lead_2,synopsis,global_rating,content_rating,tags,platform,poster_url,episodes,votes,writer,director,source_dataset
0,Move to Heaven,move to heaven,2021,2021,"Life, Drama","Lee Je Hoon, Tang Jun Sang, Hong Seung Hee, Ju...",NaN,NaN,Han Geu Roo is an autistic 20-year-old. He wor...,9.2,18+ Restricted (violence & profanity),"Uncle-Nephew Relationship,, Autism,, Death,, S...",Netflix,https://i.mydramalist.com/Rle36_4c.jpg?v=1,10 episodes,NaN,NaN,NaN,original_1500
1,Weak Hero Class 1,weak hero class 1,2022,2022,"Action, Youth, Drama","Park Ji Hoon, Choi Hyun Wook, Hong Kyung, Kim ...",NaN,NaN,Yeon Shi Eun is a model student who ranks at t...,9.1,18+ Restricted (violence & profanity),"Smart Male Lead,, Bromance,, School Bullying,,...","Wavve, iQIYI, Viki",https://i.mydramalist.com/pq2lr_4c.jpg?v=1,8 episodes,NaN,NaN,NaN,original_1500
2,Hospital Playlist Season 2,hospital playlist season 2,2021,2021,"Romance, Life, Drama, Medical","Jo Jung Suk, Yoo Yeon Seok, Jung Kyung Ho, Kim...",NaN,NaN,Everyday is extraordinary for five doctors and...,9.1,15+ - Teens 15 or older,"Multiple Mains,, Band,, Music,, Strong Female ...","TVING, Netflix",https://i.mydramalist.com/dKY0d_4c.jpg?v=1,12 episodes,NaN,NaN,NaN,original_1500
3,Flower of Evil,flower of evil,2020,2020,"Thriller, Romance, Crime, Melodrama","Lee Joon Gi, Moon Chae Won, Jang Hee Jin, Seo ...",NaN,NaN,Although Baek Hee Sung is hiding a dark secret...,9.1,15+ - Teens 15 or older,"Deception,, Family Secret,, Mystery,, Suspense...","Prime Video, Apple TV, Viki, Netflix",https://i.mydramalist.com/WAEAp_4c.jpg?v=1,16 episodes,NaN,NaN,NaN,original_1500
4,Hospital Playlist,hospital playlist,2020,2020,"Romance, Life, Drama, Medical","Jo Jung Suk, Yoo Yeon Seok, Jung Kyung Ho, Kim...",NaN,NaN,"""The stories of people going through their day...",9.1,15+ - Teens 15 or older,"Nice Male Lead,, Multiple Mains,, Slow Romance...",Netflix,https://i.mydramalist.com/RXXL6_4c.jpg?v=1,12 episodes,NaN,NaN,NaN,original_1500

Standardize the new dataset

In [20]:
new_clean = pd.DataFrame()

new_clean["title"] = new_df["title"]
new_clean["normalized_title"] = new_clean["title"].apply(normalize_title)

new_clean["start_year"] = pd.to_datetime(
    new_df["startYear"], errors="coerce"
).dt.year

new_clean["end_year"] = pd.to_datetime(
    new_df["endYear"], errors="coerce"
).dt.year

new_clean["genres"] = new_df["genres"]

new_clean["main_lead_1"] = new_df["mainLead1"]
new_clean["main_lead_2"] = new_df["mainLead2"]

new_clean["cast"] = (
    new_df["mainLead1"].fillna("").astype(str)
    + ", "
    + new_df["mainLead2"].fillna("").astype(str)
)

new_clean["cast"] = new_clean["cast"].str.strip(", ")

new_clean["synopsis"] = new_df["synopsis"]
new_clean["global_rating"] = pd.to_numeric(new_df["rating"], errors="coerce")

new_clean["content_rating"] = np.nan
new_clean["tags"] = np.nan

# Platform is missing in the new dataset, so we mark it honestly as Unknown
new_clean["platform"] = "Unknown"

new_clean["poster_url"] = new_df["image_url"]
new_clean["episodes"] = np.nan

new_clean["votes"] = pd.to_numeric(new_df["votes"], errors="coerce")
new_clean["writer"] = new_df["writer"]
new_clean["director"] = new_df["director"]

new_clean["source_dataset"] = "kaggle_2021_2025"

new_clean.head()

,title,normalized_title,start_year,end_year,genres,main_lead_1,main_lead_2,cast,synopsis,global_rating,content_rating,tags,platform,poster_url,episodes,votes,writer,director,source_dataset
0,"Genie, Make a Wish",genie make a wish,2025,2025,"Comedy,Fantasy,Romance",Kim Woo-bin,Bae Suzy,"Kim Woo-bin, Bae Suzy","Jinn, a genie who awakens after a thousand yea...",6.4,NaN,NaN,Unknown,https://m.media-amazon.com/images/M/MV5BOWM4Mj...,NaN,7700,['Kim Eun-sook'],['Lee Byeong-heon'],kaggle_2021_2025
1,Squid Game,squid game,2021,2021,"Action,Drama,Mystery",Lee Jung-jae,Greg Chun,"Lee Jung-jae, Greg Chun",Hundreds of cash-strapped players accept a str...,8.0,NaN,NaN,Unknown,https://m.media-amazon.com/images/M/MV5BYTU3ZD...,NaN,723000,['Hwang Dong-hyuk'],['Hwang Dong-hyuk'],kaggle_2021_2025
2,When Life Gives You Tangerines,when life gives you tangerines,2025,2025,"Drama,History,Romance",IU,IU,"IU, IU","In Jeju, a spirited girl and a steadfast boy's...",9.1,NaN,NaN,Unknown,https://m.media-amazon.com/images/M/MV5BZTBhZT...,NaN,29000,"['Im Sang-choon', 'Lim Sang-Chung', 'Kim Won-s...",['Kim Won-seok'],kaggle_2021_2025
3,Typhoon Family,typhoon family,2025,2025,Drama,Lee Jun-ho,Minha Kim,"Lee Jun-ho, Minha Kim","CEO Kang Tae Pung runs Typhoon Company, his fa...",8.1,NaN,NaN,Unknown,https://m.media-amazon.com/images/M/MV5BYzhkZT...,NaN,296,['\\N'],['Lee Na-jeong'],kaggle_2021_2025
4,All of Us Are Dead,all of us are dead,2022,2022,"Action,Drama,Fantasy",Park Ji-hu,Yoon Chan-young,"Park Ji-hu, Yoon Chan-young",A high school becomes ground zero for a zombie...,7.6,NaN,NaN,Unknown,https://m.media-amazon.com/images/M/MV5BZDY4Zm...,NaN,85000,"['Seong-il Cheon', 'Joo Dong-Geun']","['J.Q. Lee', 'Kim Nam-Soo']",kaggle_2021_2025

In [21]:
final_columns = [
    "title",
    "normalized_title",
    "start_year",
    "end_year",
    "genres",
    "cast",
    "main_lead_1",
    "main_lead_2",
    "synopsis",
    "global_rating",
    "content_rating",
    "tags",
    "platform",
    "poster_url",
    "episodes",
    "votes",
    "writer",
    "director",
    "source_dataset"
]

old_clean = old_clean[final_columns]
new_clean = new_clean[final_columns]

In [22]:
print("Old clean shape:", old_clean.shape)
print("New clean shape:", new_clean.shape)

print("\nColumns match?")
print(old_clean.columns.tolist() == new_clean.columns.tolist())

print("\nOld clean columns:")
print(old_clean.columns.tolist())

print("\nNew clean columns:")
print(new_clean.columns.tolist())

Old clean shape: (1647, 19)
New clean shape: (508, 19)

Columns match?
True

Old clean columns:
['title', 'normalized_title', 'start_year', 'end_year', 'genres', 'cast', 'main_lead_1', 'main_lead_2', 'synopsis', 'global_rating', 'content_rating', 'tags', 'platform', 'poster_url', 'episodes', 'votes', 'writer', 'director', 'source_dataset']

New clean columns:
['title', 'normalized_title', 'start_year', 'end_year', 'genres', 'cast', 'main_lead_1', 'main_lead_2', 'synopsis', 'global_rating', 'content_rating', 'tags', 'platform', 'poster_url', 'episodes', 'votes', 'writer', 'director', 'source_dataset']

### Combine both datasets

In [23]:
combined_df = pd.concat([old_clean, new_clean], ignore_index=True)

print("Combined dataset shape:", combined_df.shape)
combined_df.head()

Combined dataset shape: (2155, 19)

,title,normalized_title,start_year,end_year,genres,cast,main_lead_1,main_lead_2,synopsis,global_rating,content_rating,tags,platform,poster_url,episodes,votes,writer,director,source_dataset
0,Move to Heaven,move to heaven,2021,2021,"Life, Drama","Lee Je Hoon, Tang Jun Sang, Hong Seung Hee, Ju...",NaN,NaN,Han Geu Roo is an autistic 20-year-old. He wor...,9.2,18+ Restricted (violence & profanity),"Uncle-Nephew Relationship,, Autism,, Death,, S...",Netflix,https://i.mydramalist.com/Rle36_4c.jpg?v=1,10 episodes,NaN,NaN,NaN,original_1500
1,Weak Hero Class 1,weak hero class 1,2022,2022,"Action, Youth, Drama","Park Ji Hoon, Choi Hyun Wook, Hong Kyung, Kim ...",NaN,NaN,Yeon Shi Eun is a model student who ranks at t...,9.1,18+ Restricted (violence & profanity),"Smart Male Lead,, Bromance,, School Bullying,,...","Wavve, iQIYI, Viki",https://i.mydramalist.com/pq2lr_4c.jpg?v=1,8 episodes,NaN,NaN,NaN,original_1500
2,Hospital Playlist Season 2,hospital playlist season 2,2021,2021,"Romance, Life, Drama, Medical","Jo Jung Suk, Yoo Yeon Seok, Jung Kyung Ho, Kim...",NaN,NaN,Everyday is extraordinary for five doctors and...,9.1,15+ - Teens 15 or older,"Multiple Mains,, Band,, Music,, Strong Female ...","TVING, Netflix",https://i.mydramalist.com/dKY0d_4c.jpg?v=1,12 episodes,NaN,NaN,NaN,original_1500
3,Flower of Evil,flower of evil,2020,2020,"Thriller, Romance, Crime, Melodrama","Lee Joon Gi, Moon Chae Won, Jang Hee Jin, Seo ...",NaN,NaN,Although Baek Hee Sung is hiding a dark secret...,9.1,15+ - Teens 15 or older,"Deception,, Family Secret,, Mystery,, Suspense...","Prime Video, Apple TV, Viki, Netflix",https://i.mydramalist.com/WAEAp_4c.jpg?v=1,16 episodes,NaN,NaN,NaN,original_1500
4,Hospital Playlist,hospital playlist,2020,2020,"Romance, Life, Drama, Medical","Jo Jung Suk, Yoo Yeon Seok, Jung Kyung Ho, Kim...",NaN,NaN,"""The stories of people going through their day...",9.1,15+ - Teens 15 or older,"Nice Male Lead,, Multiple Mains,, Slow Romance...",Netflix,https://i.mydramalist.com/RXXL6_4c.jpg?v=1,12 episodes,NaN,NaN,NaN,original_1500

In [24]:
duplicate_titles = (
    combined_df[combined_df.duplicated(subset=["normalized_title"], keep=False)]
    .sort_values("normalized_title")
)

print("Number of duplicate rows based on normalized title:", duplicate_titles.shape[0])
print("Number of unique duplicate titles:", duplicate_titles["normalized_title"].nunique())

duplicate_titles[[
    "title",
    "normalized_title",
    "start_year",
    "global_rating",
    "platform",
    "poster_url",
    "source_dataset"
]].head(30)

Number of duplicate rows based on normalized title: 393
Number of unique duplicate titles: 196

,title,normalized_title,start_year,global_rating,platform,poster_url,source_dataset
2133,A Good Supper,a good supper,2021,4.7,Unknown,https://m.media-amazon.com/images/M/MV5BODFhMD...,kaggle_2021_2025
1639,A Good Supper,a good supper,2021,6.6,Viki,https://i.mydramalist.com/Z20bY_4c.jpg?v=1,original_1500
1779,A Model Family,a model family,2022,6.6,Unknown,https://m.media-amazon.com/images/M/MV5BMmEwZj...,kaggle_2021_2025
949,A Model Family,a model family,2022,7.5,Netflix,https://i.mydramalist.com/R6YzP_4c.jpg?v=1,original_1500
1523,A Superior Day,a superior day,2022,7.0,Viki,https://i.mydramalist.com/BPBo7_4c.jpg?v=1,original_1500
2078,A Superior Day,a superior day,2022,5.9,Unknown,https://m.media-amazon.com/images/M/MV5BMjFjOD...,kaggle_2021_2025
1815,Adamas,adamas,2022,7.0,Unknown,https://m.media-amazon.com/images/M/MV5BMzQ5OG...,kaggle_2021_2025
751,Adamas,adamas,2022,7.7,"Disney+, Disney+ Hotstar",https://i.mydramalist.com/ZlzzJ_4c.jpg?v=1,original_1500
1808,Adult Trainee,adult trainee,2021,6.7,Unknown,https://m.media-amazon.com/images/M/MV5BMzVhMT...,kaggle_2021_2025
610,Adult Trainee,adult trainee,2021,7.9,TVING,https://i.mydramalist.com/e48qd_4c.jpg?v=1,original_1500
1836,Again My Life,again my life,2022,7.7,Unknown,https://m.media-amazon.com/images/M/MV5BNjMyOD...,kaggle_2021_2025
230,Again My Life,again my life,2022,8.3,Viki,https://i.mydramalist.com/XDKww_4c.jpg?v=1,original_1500
1860,Agency,agency,2023,7.8,Unknown,https://m.media-amazon.com/images/M/MV5BODI5Nm...,kaggle_2021_2025
398,Agency,agency,2023,8.1,"iQIYI, Viki",https://i.mydramalist.com/pEK1y_4c.jpg?v=1,original_1500
1653,Alchemy of Souls,alchemy of souls,2022,8.7,Unknown,https://m.media-amazon.com/images/M/MV5BOGFhNG...,kaggle_2021_2025
5,Alchemy of Souls,alchemy of souls,2022,9.1,Netflix,https://i.mydramalist.com/Beg4z_4c.jpg?v=1,original_1500
1651,All of Us Are Dead,all of us are dead,2022,7.6,Unknown,https://m.media-amazon.com/images/M/MV5BZDY4Zm...,kaggle_2021_2025
136,All of Us Are Dead,all of us are dead,2022,8.5,Netflix,https://i.mydramalist.com/WRQmX_4c.jpg?v=1,original_1500
592,Anna,anna,2022,7.9,Prime Video,https://i.mydramalist.com/Wp4LW_4c.jpg?v=1,original_1500
1784,Anna,anna,2022,7.0,Unknown,https://m.media-amazon.com/images/M/MV5BMTQ5Zm...,kaggle_2021_2025
201,"At a Distance, Spring Is Green",at a distance spring is green,2021,8.3,"Apple TV, iQIYI, Viki",https://i.mydramalist.com/2Pxe2_4c.jpg?v=1,original_1500
1814,"At A Distance, Spring Is Green",at a distance spring is green,2021,7.8,Unknown,https://m.media-amazon.com/images/M/MV5BYjg3ZD...,kaggle_2021_2025
1735,Bad and Crazy,bad and crazy,2021,8.0,Unknown,https://m.media-amazon.com/images/M/MV5BMjEzNT...,kaggle_2021_2025
108,Bad and Crazy,bad and crazy,2021,8.5,"iQIYI, Netflix, Prime Video, TVING",https://i.mydramalist.com/RVbJz_4c.jpg?v=1,original_1500
1638,Bad Girlfriend,bad girlfriend,2022,6.6,"KOK TV, Viki",https://i.mydramalist.com/4ROEJ_4c.jpg?v=1,original_1500
2001,Bad Girlfriend,bad girlfriend,2022,5.8,Unknown,https://m.media-amazon.com/images/M/MV5BM2Y3ZW...,kaggle_2021_2025
283,Bad Prosecutor,bad prosecutor,2022,8.2,"Wavve, Viki",https://i.mydramalist.com/Xnvxn_4c.jpg?v=1,original_1500
1990,Bad Prosecutor,bad prosecutor,2022,7.5,Unknown,https://m.media-amazon.com/images/M/MV5BYjg2M2...,kaggle_2021_2025
2121,Be My Dream Family,be my dream family,2021,8.2,Unknown,https://m.media-amazon.com/images/M/MV5BOGVmZj...,kaggle_2021_2025
416,Be My Dream Family,be my dream family,2021,8.1,KBS World,https://i.mydramalist.com/XRdJp_4c.jpg?v=1,original_1500

In [25]:
def is_valid_value(value, treat_unknown_as_missing=True):
    """
    Checks whether a value is useful.
    Treats blanks, NaN, None, and optionally 'Unknown' as missing.
    """
    if pd.isna(value):
        return False
    
    if isinstance(value, str):
        cleaned = value.strip()
        if cleaned == "":
            return False
        
        missing_strings = {"nan", "none", "null", "n/a", "na"}
        
        if treat_unknown_as_missing:
            missing_strings.add("unknown")
        
        if cleaned.lower() in missing_strings:
            return False
    
    return True


def first_valid_from(group, column, source=None, treat_unknown_as_missing=True):
    """
    Gets the first useful value from a specific source if provided.
    """
    if source:
        group = group[group["source_dataset"] == source]
    
    for value in group[column]:
        if is_valid_value(value, treat_unknown_as_missing=treat_unknown_as_missing):
            return value
    
    return np.nan


def longest_valid_text(group, column):
    """
    For fields like synopsis, keeps the longest available text.
    """
    valid_values = [
        value for value in group[column]
        if is_valid_value(value)
    ]
    
    if not valid_values:
        return np.nan
    
    return max(valid_values, key=lambda x: len(str(x)))

In [26]:
def merge_drama_group(group):
    """
    Merges duplicate drama rows into one best possible row.
    
    Priority logic:
    - Keep old dataset values for platform, year, tags, content rating, episodes
    - Keep new dataset values for votes, writer, director, and main leads
    - Keep the longest synopsis
    - Keep original rating when available for consistency with the old project
    """
    
    row = {}
    
    old_source = "original_1500"
    new_source = "kaggle_2021_2025"
    
    # Basic identity fields
    row["title"] = first_valid_from(group, "title", old_source)
    if not is_valid_value(row["title"]):
        row["title"] = first_valid_from(group, "title", new_source)
    
    row["normalized_title"] = first_valid_from(group, "normalized_title", old_source)
    if not is_valid_value(row["normalized_title"]):
        row["normalized_title"] = first_valid_from(group, "normalized_title", new_source)
    
    # Year fields: prefer old dataset because your output shows new start_year is often NaN
    row["start_year"] = first_valid_from(group, "start_year", old_source)
    if not is_valid_value(row["start_year"]):
        row["start_year"] = first_valid_from(group, "start_year", new_source)
    
    row["end_year"] = first_valid_from(group, "end_year", old_source)
    if not is_valid_value(row["end_year"]):
        row["end_year"] = first_valid_from(group, "end_year", new_source)
    
    # Drama details
    row["genres"] = first_valid_from(group, "genres", old_source)
    if not is_valid_value(row["genres"]):
        row["genres"] = first_valid_from(group, "genres", new_source)
    
    # Old cast is usually richer; new has only mainLead1 and mainLead2
    row["cast"] = first_valid_from(group, "cast", old_source)
    if not is_valid_value(row["cast"]):
        row["cast"] = first_valid_from(group, "cast", new_source)
    
    # New dataset has structured lead columns
    row["main_lead_1"] = first_valid_from(group, "main_lead_1", new_source)
    row["main_lead_2"] = first_valid_from(group, "main_lead_2", new_source)
    
    # Keep longest available synopsis
    row["synopsis"] = longest_valid_text(group, "synopsis")
    
    # Prefer old rating for consistency with existing app
    row["global_rating"] = first_valid_from(group, "global_rating", old_source)
    if not is_valid_value(row["global_rating"]):
        row["global_rating"] = first_valid_from(group, "global_rating", new_source)
    
    # Old-only app fields
    row["content_rating"] = first_valid_from(group, "content_rating", old_source)
    row["tags"] = first_valid_from(group, "tags", old_source)
    
    # Platform: prefer old because new dataset has Unknown
    row["platform"] = first_valid_from(group, "platform", old_source)
    if not is_valid_value(row["platform"]):
        row["platform"] = "Unknown"
    
    # Poster: prefer old MyDramaList poster if available, otherwise use new image_url
    row["poster_url"] = first_valid_from(group, "poster_url", old_source)
    if not is_valid_value(row["poster_url"]):
        row["poster_url"] = first_valid_from(group, "poster_url", new_source)
    
    row["episodes"] = first_valid_from(group, "episodes", old_source)
    
    # New-only useful future ML fields
    row["votes"] = first_valid_from(group, "votes", new_source)
    row["writer"] = first_valid_from(group, "writer", new_source)
    row["director"] = first_valid_from(group, "director", new_source)
    
    # Track whether row came from one or both datasets
    sources = sorted(group["source_dataset"].dropna().unique())
    row["source_dataset"] = " + ".join(sources)
    
    return row

In [27]:
merged_rows = []

for normalized_title, group in combined_df.groupby("normalized_title", dropna=False):
    merged_rows.append(merge_drama_group(group))

master_df = pd.DataFrame(merged_rows)

# Keep final column order
master_df = master_df[final_columns]

print("Combined dataset before deduplication:", combined_df.shape)
print("Master dataset after smart deduplication:", master_df.shape)
print("Rows removed:", combined_df.shape[0] - master_df.shape[0])
print("Remaining duplicate normalized titles:", master_df.duplicated(subset=["normalized_title"]).sum())

Combined dataset before deduplication: (2155, 19)
Master dataset after smart deduplication: (1958, 19)
Rows removed: 197
Remaining duplicate normalized titles: 0

In [28]:
check_titles = [
    "alchemy of souls",
    "anna",
    "a model family",
    "again my life",
    "all of us are dead"
]

master_df[
    master_df["normalized_title"].isin(check_titles)
][[
    "title",
    "normalized_title",
    "start_year",
    "global_rating",
    "platform",
    "votes",
    "writer",
    "director",
    "poster_url",
    "source_dataset"
]]

,title,normalized_title,start_year,global_rating,platform,votes,writer,director,poster_url,source_dataset
38,A Model Family,a model family,2022,7.5,Netflix,1700.0,"['Lee Jae-gon', 'Kim Jin-woo']",['\\N'],https://i.mydramalist.com/R6YzP_4c.jpg?v=1,kaggle_2021_2025 + original_1500
67,Again My Life,again my life,2022,8.3,Viki,1900.0,"['Lee Byeong-heon', 'Lee Hae-nal', 'Jai', 'Yoo...","['Chul-soo Han', 'Min-Yong Kim']",https://i.mydramalist.com/XDKww_4c.jpg?v=1,kaggle_2021_2025 + original_1500
74,Alchemy of Souls,alchemy of souls,2022,9.1,Netflix,26000.0,"['Hong Jeong-eun', 'Hong Mi-ran']",['Park Joon-hwa'],https://i.mydramalist.com/Beg4z_4c.jpg?v=1,kaggle_2021_2025 + original_1500
87,All of Us Are Dead,all of us are dead,2022,8.5,Netflix,85000.0,"['Seong-il Cheon', 'Joo Dong-Geun']","['J.Q. Lee', 'Kim Nam-Soo']",https://i.mydramalist.com/WRQmX_4c.jpg?v=1,kaggle_2021_2025 + original_1500
98,Anna,anna,2022,7.9,Prime Video,2100.0,['Lee Joo-young'],['Lee Joo-young'],https://i.mydramalist.com/Wp4LW_4c.jpg?v=1,kaggle_2021_2025 + original_1500

In [29]:
print("Missing values in master dataset:")
display(master_df.isna().sum().sort_values(ascending=False))

print("\nPlatform value counts:")
display(master_df["platform"].value_counts(dropna=False).head(20))

print("\nSource dataset counts:")
display(master_df["source_dataset"].value_counts())

Missing values in master dataset:

director            1450
writer              1450
votes               1450
main_lead_1         1450
main_lead_2         1450
tags                 337
episodes             318
content_rating       318
synopsis               7
title                  0
platform               0
poster_url             0
global_rating          0
normalized_title       0
cast                   0
genres                 0
end_year               0
start_year             0
source_dataset         0
dtype: int64

Platform value counts:

platform
Viki                     394
Unknown                  318
Netflix                  163
Apple TV, Viki            52
KBS World                 49
SBS World, Viki           44
Viki, Netflix             38
WeTV                      24
iQIYI, Viki               24
Viki, WeTV                22
iQIYI                     20
Tubi                      20
Prime Video, Viki         19
SBS World                 19
Prime Video               18
KBS World, Viki           17
TVING, Netflix            15
PlayList Global           13
KOK TV                    12
PlayList Global, WeTV     11
Name: count, dtype: int64

Source dataset counts:

source_dataset
original_1500                       1450
kaggle_2021_2025                     318
kaggle_2021_2025 + original_1500     190
Name: count, dtype: int64

## Export Final Master Dataset

The cleaned and deduplicated dataset is exported as `kdrama_master_updated.csv`. This file will become the main dataset used by the Streamlit app.

In [30]:
# Export final master dataset
output_path = DATA_DIR / "kdrama_master_updated.csv"

master_df.to_csv(output_path, index=False, encoding="utf-8")

print(f"Master dataset exported successfully to: {output_path}")
print("Final master dataset shape:", master_df.shape)

Master dataset exported successfully to: ../data/kdrama_master_updated.csv
Final master dataset shape: (1958, 19)

In [31]:
# Validate exported file
exported_df = pd.read_csv(output_path)

print("Exported dataset shape:", exported_df.shape)
print("Columns match master_df?")
print(exported_df.columns.tolist() == master_df.columns.tolist())

print("Remaining duplicate normalized titles:")
print(exported_df.duplicated(subset=["normalized_title"]).sum())

exported_df.head()

Exported dataset shape: (1958, 19)
Columns match master_df?
True
Remaining duplicate normalized titles:
0

,title,normalized_title,start_year,end_year,genres,cast,main_lead_1,main_lead_2,synopsis,global_rating,content_rating,tags,platform,poster_url,episodes,votes,writer,director,source_dataset
0,1% of Anything,1 of anything,2003,2003,"Comedy, Romance","Kang Dong Won, Kim Jung Hwa, Han Hye Jin, Lee ...",NaN,NaN,Kim Jung Hwa is a young and sincere middle sch...,7.0,13+ - Teens 13 or older,"Arranged Relationship,, Love/Hate Relationship...",Netflix,https://i.mydramalist.com/NdPpYc.jpg?v=1,26 episodes,NaN,NaN,NaN,original_1500
1,100 Days My Prince,100 days my prince,2018,2018,"Historical, Comedy, Romance, Drama","Doh Kyung Soo, Nam Ji Hyun, Kim Seon Ho, Han S...",NaN,NaN,"Lee Yul, Crown Prince of Joseon, is a perfecti...",8.3,15+ - Teens 15 or older,"Amnesia,, Hidden Identity,, Marriage Of Conven...","WeTV, Netflix, Apple TV, iQIYI, Viki",https://i.mydramalist.com/p0yXrc.jpg?v=1,16 episodes,NaN,NaN,NaN,original_1500
2,100% Era,100 era,2021,2021,"Romance, Youth","Yoo Jung Woo, Lee Soo Min, Yeo Ji Min, Logan, ...",NaN,NaN,100% Era imagines the post-corona future. How ...,7.5,15+ - Teens 15 or older,"COVID-19,, Rivalry,, Steamy Kiss,, Miniseries,...",Netflix,https://i.mydramalist.com/EyqL5_4c.jpg?v=1,8 episodes,NaN,NaN,NaN,original_1500
3,109 Strange Things,109 strange things,2017,2017,"Romance, Youth, Sci-Fi","Choi Tae Joon, Jung Chae Yeon, Cho Yi Hyun, K...",NaN,NaN,"When a robot comes from the future, will a phi...",6.6,Not Yet Rated,"Short Length Series,, Web Series,, Student Fem...","视频中国-China Video, Viki",https://i.mydramalist.com/A7eQvc.jpg?v=1,6 episodes,NaN,NaN,NaN,original_1500
4,18 Again,18 again,2020,2020,"Romance, Life, Drama, Fantasy","Kim Ha Neul, Yoon Sang Hyun, Lee Do Hyun, Roh ...",NaN,NaN,"After nearly twenty years of marriage, Jung Da...",8.7,15+ - Teens 15 or older,"Second Chance,, First Love,, Father-Son Relati...","TVING, Netflix",https://i.mydramalist.com/xnNnq_4c.jpg?v=1,16 episodes,NaN,NaN,NaN,original_1500

In [32]:
exported_df["start_year"].value_counts().sort_index().tail(10)

start_year
2016    104
2017    123
2018    144
2019    152
2020    145
2021    184
2022    191
2023    118
2024     96
2025     59
Name: count, dtype: int64

In [33]:
exported_df[
    exported_df["start_year"] >= 2024
][[
    "title",
    "start_year",
    "global_rating",
    "platform",
    "source_dataset"
]].head(20)

,title,start_year,global_rating,platform,source_dataset
31,A Killer Paradox,2024,7.1,Unknown,kaggle_2021_2025
45,A Shop for Killers,2024,8.0,Unknown,kaggle_2021_2025
52,A Virtuous Business,2024,7.3,Unknown,kaggle_2021_2025
71,Agents of Mystery,2024,6.7,Unknown,kaggle_2021_2025
79,A-List to Playlist,2024,7.4,Unknown,kaggle_2021_2025
135,Bad Memory Eraser,2024,6.2,Unknown,kaggle_2021_2025
156,Beauty and Mr. Romantic,2024,5.7,Unknown,kaggle_2021_2025
165,Begins Youth,2024,8.5,Unknown,kaggle_2021_2025
196,Bittersweet Hell,2024,6.7,Unknown,kaggle_2021_2025
203,Blood Free,2024,7.1,Unknown,kaggle_2021_2025
219,Branding in Seongsu,2024,6.5,Unknown,kaggle_2021_2025
223,Brewing Love,2024,7.0,Unknown,kaggle_2021_2025
232,Business as Usual,2025,6.9,Unknown,kaggle_2021_2025
248,Captivating the King,2024,7.6,Unknown,kaggle_2021_2025
256,Check-in Hanyang,2024,6.6,Unknown,kaggle_2021_2025
266,Chicken Nugget,2024,5.1,Unknown,kaggle_2021_2025
267,Chief Detective 1958,2024,7.8,Unknown,kaggle_2021_2025
277,Chunhwa Love Story,2025,5.5,Unknown,kaggle_2021_2025
279,Cinderella at 2 AM,2024,6.9,Unknown,kaggle_2021_2025
280,Cinderella Game,2024,7.6,Unknown,kaggle_2021_2025

## Create Platform Override File

The 2021–2025 dataset does not include streaming platform information. To avoid hardcoding platform values in the app, a separate `platform_overrides.csv` file is created. This file can be manually updated over time and later merged into the app through the data loader.

In [34]:
# Create a starter platform override file for dramas with Unknown platform

platform_override_path = DATA_DIR / "platform_overrides.csv"

unknown_platform_df = master_df[
    master_df["platform"].fillna("Unknown").str.strip().str.lower() == "unknown"
][["title", "normalized_title"]].copy()

unknown_platform_df["platform"] = ""
unknown_platform_df["notes"] = "Manual platform lookup needed"

unknown_platform_df.to_csv(platform_override_path, index=False, encoding="utf-8")

print(f"Platform override file created at: {platform_override_path}")
print("Number of dramas needing platform lookup:", unknown_platform_df.shape[0])

unknown_platform_df.head(20)

Platform override file created at: ../data/platform_overrides.csv
Number of dramas needing platform lookup: 318

,title,normalized_title,platform,notes
22,A Bloody Lucky Day,a bloody lucky day,,Manual platform lookup needed
23,A Breeze of Love,a breeze of love,,Manual platform lookup needed
28,A Good Day to Be a Dog,a good day to be a dog,,Manual platform lookup needed
31,A Killer Paradox,a killer paradox,,Manual platform lookup needed
39,A Nation of Broth,a nation of broth,,Manual platform lookup needed
45,A Shop for Killers,a shop for killers,,Manual platform lookup needed
51,A Time Called You,a time called you,,Manual platform lookup needed
52,A Virtuous Business,a virtuous business,,Manual platform lookup needed
54,A Wonderful Sight,a wonderful sight,,Manual platform lookup needed
71,Agents of Mystery,agents of mystery,,Manual platform lookup needed
78,Alien Stage,alien stage,,Manual platform lookup needed
79,A-List to Playlist,alist to playlist,,Manual platform lookup needed
92,Amor Fati,amor fati,,Manual platform lookup needed
103,Apple of My Eye,apple of my eye,,Manual platform lookup needed
107,Armored Saurus,armored saurus,,Manual platform lookup needed
135,Bad Memory Eraser,bad memory eraser,,Manual platform lookup needed
144,Baradeon Bada,baradeon bada,,Manual platform lookup needed
156,Beauty and Mr. Romantic,beauty and mr romantic,,Manual platform lookup needed
157,Bebefinn,bebefinn,,Manual platform lookup needed
162,Bee & Puppycat: Lazy in Space,bee puppycat lazy in space,,Manual platform lookup needed

In [35]:
platform_overrides = pd.read_csv(platform_override_path)

print("Platform override file shape:", platform_overrides.shape)
print("Columns:")
print(platform_overrides.columns.tolist())

platform_overrides.head()

Platform override file shape: (318, 4)
Columns:
['title', 'normalized_title', 'platform', 'notes']

,title,normalized_title,platform,notes
0,A Bloody Lucky Day,a bloody lucky day,NaN,Manual platform lookup needed
1,A Breeze of Love,a breeze of love,NaN,Manual platform lookup needed
2,A Good Day to Be a Dog,a good day to be a dog,NaN,Manual platform lookup needed
3,A Killer Paradox,a killer paradox,NaN,Manual platform lookup needed
4,A Nation of Broth,a nation of broth,NaN,Manual platform lookup needed